name: Workflow on Push into Main
run-name: ${{ github.actor }} triggered workflow

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  trigger-build:
    name: Lint, Prettier, Dep Graph and Build
    uses: ./.github/workflows/reusable-code-quality.yml
    secrets: inherit

  trigger-jest:
    name: Jest Tests
    needs: trigger-build
    uses: ./.github/workflows/reusable-unit-tests.yml
    secrets: inherit

  trigger-playwright:
    name: Playwright Tests
    needs: trigger-build
    uses: ./.github/workflows/reusable-e2e.yml
    secrets: inherit

  trigger-deploy:
    name: Build and Publish Docker image
    needs: [trigger-build, trigger-jest, trigger-playwright]
    uses: ./.github/workflows/reusable-deploy.yml
    secrets: inherit
