name: Reusable - Code Quality Checks (Prettier, Linting, Dependency Graph)

on:
  workflow_call:

jobs:
  run-code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/
          scope: '@smartive-education'
      - name: Install dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "@smartive-education:registry=https://npm.pkg.github.com" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ env.NODE_AUTH_TOKEN }}" > ~/.npmrc
          npm ci
      - name: Run Prettier
        run: npm run prettier:check
      - name: Run ESLint
        run: npm run lint
      - name: Run Dependency Graph
        run: npm run dep-cruise:validate
      - name: Build
        run: npm run build

